### ISSUE TITLE
Integrate subcriptoins on homepage

### ISSUE THREAD

**Issue by cirotix** [briefmnews/briefme_cms#108]
http://share.upian.net/-Brief.me/01_Home/01_Home_briefme_150115_05.jpg

Please check with Karim if this is the final version, there are a lot of them in the share

**Comment by manudurgoni** [comment]
okay, now its more : understandable http://share.upian.net/-Brief.me/01_Home

**Comment by cirotix** [comment]
Two small typos: 

70,8 -> 70,80
![image](https://cloud.githubusercontent.com/assets/147133/5777636/c309c500-9d94-11e4-8191-0fc7fc28f06a.png)

J'essai -> J'essaie 
![image](https://cloud.githubusercontent.com/assets/147133/5777651/e341b9c2-9d94-11e4-8963-eb9dcaaa37a5.png)
