### ISSUE TITLE
There is a plan merge tag in Mailchimp

### ISSUE THREAD

**Issue by cirotix** [briefmnews/briefme_cms#110]
We need to to be able to have a segment in Mailchimp to send the newsletter to this segment

**Comment by lmauriac** [comment]
Champs title

http://www.brief.me:8010/

--> Brief.me - Le mini-journal par e-mail pour y voir plus clair dans l'actualité

http://www.brief.me:8010/inscription-plus

--> Brief.me - Votre abonnement d'essai est presque validé

http://www.brief.me:8010/inscription-confirm

--> Brief.me - Merci pour votre inscription

http://www.brief.me:8010/compte/

--> Brief.me - Mon compte

http://www.brief.me:8010/abonnement

--> Brief.me - Je m'abonne

**Comment by cirotix** [comment]
Oops wrong ticket
