### ISSUE TITLE
Footer must have a fixed height

### ISSUE THREAD

**Issue by cirotix** [briefmnews/briefme_cms#117]
See http://www.brief.me:8010/inscription

![image](https://cloud.githubusercontent.com/assets/147133/5784747/c86f51fa-9dcf-11e4-91e1-b4a7921d2deb.png)

**Comment by manudurgoni** [comment]
I'm not a big fan of this solution. I already thought about that and I think it increases the javascript run time (especially on mobile) on each page to determine if the height of the Body is higher or not that the window's height. 

In addition, this page has the module with the different subscriptions, right ?

![Inscription]
(http://s3.amazonaws.com/awesome_screenshot/7089189?AWSAccessKeyId=0R7FMW7AXRVCYMAPTPR2&Expires=1421658814&Signature=7OrBgSgPkG7MYb51RtWok%2B91JZI%3D)

**Comment by cirotix** [comment]
Yes for this page, but there other short pages, such as recover email.
