### ISSUE TITLE
Texts in question marks in forms

### ISSUE THREAD

**Issue by cirotix** [briefmnews/briefme_cms#120]

**Comment by lmauriac** [comment]
Brief.me se construit pour ses lecteurs et avec eux. C'est pour cette raison que nous sommes intéressés par vos domaines d'expertise ou votre lieu d'habitation. Nous pourrons ainsi vous contacter lorsque nous traiterons de sujets particuliers (santé, urbanisme, éducation, etc.) ou d'événements se produisant dans des pays étrangers. Ces renseignements sont bien sûr facultatifs.
