### ISSUE TITLE
Reestablish tooltip in Brief.me e-mails

### ISSUE THREAD

**Issue by lmauriac** [briefmnews/briefme_cms#129]
The last Brief.me email did not display tooltips (infobulles) as usual (including the name of the source and the title of the article).
The tooltips were entered as usual in the BO but they were not displayed in the email.
Here is the comment we received from Seb Chevillet :

![2015-01-19_171249](https://cloud.githubusercontent.com/assets/10548982/5803400/73adca80-9ffe-11e4-95db-014f9601db72.png)

**Comment by cirotix** [comment]
Need to re apply the title redactor patch
