### ISSUE TITLE
Modif inscription-confirm

### ISSUE THREAD

**Issue by lmauriac** [briefmnews/briefme_cms#140]
http://www.brief.me:8010/inscription-confirm

Cette mention apparaît entre le logo et "bienvenue" (voir capture d'écran) :
Votre profil n'est pas encore validé renvoyer l'email de validation

![2015-01-20_213814](https://cloud.githubusercontent.com/assets/10548982/5825747/026e0ab0-a0ee-11e4-9a27-eee7a31c26e3.png)

Modif texte
Vous allez recevoir dans les prochaines minutes un e-mail de confirmation.
--> Vous allez recevoir dans les prochaines minutes un e-mail de confirmation avec un lien pour valider votre inscription.

Le temps que ce message arrive
--> En attendant

L'adresse e-mail que vous avez soumise contient une erreur. Vous pouvez la mettre à jour sur votre compte.
--> Dernière phrase à supprimer ? Cf. remarque Eric.

NB : E-mail de confirmation pas encore corrigé mais ticket déjà en cours (texte bouton et dernière phrase).

**Comment by cirotix** [comment]
> http://www.brief.me:8010/inscription-confirm

> Cette mention apparaît entre le logo et "bienvenue" (voir capture d'écran) :
> Votre profil n'est pas encore validé renvoyer l'email de validation

C'est normal, c'est le design. Ça permet au utilisateur qui n'ont pas reçu leur e-mail de confirmation de le recevoir de nouveau.

**Comment by cirotix** [comment]
Les autres points sont ok. 

Le point soulevé par Eric n'est plus valide puisque maintenant les utilisateurs sont automatiquement connectés pendant leur parcourt d'inscription. Ils peuvent donc aller mettre à jour leur compte et recevoir de nouveau l'email de confirmation.

**Comment by lmauriac** [comment]
Je ne comprends pas ce point :
C'est normal, c'est le design. Ça permet au utilisateur qui n'ont pas reçu
leur e-mail de confirmation de le recevoir de nouveau.

Si ça doit rester, ça ne me semble pas clair comme formulation.


2015-01-21 0:01 GMT+01:00 Damien Cirotteau <notifications@github.com>:

**Comment by cirotix** [comment]
Peux tu proposer une autre formulation ?

**Comment by lmauriac** [comment]
Ca serait plus logique de le mettre en bas de la page après les
explications sur le spam, etc.

Deux possibilités

1-

Bandeau en haut : Votre inscription n'est pas encore validée.
Mention en bas (après point 3) : Un problème ? <lien>Renvoyer l'e-mail de
confirmation</lien>.

2-

Mention en bas (après point 3) :
Votre inscription ne sera effective qu'après validation de l'e-mail de
confirmation. Un problème ? <lien>Renvoyer l'e-mail de confirmation</lien>.


On Wed, Jan 21, 2015 at 10:21 AM, Damien Cirotteau <notifications@github.com

**Comment by cirotix** [comment]
Le truc c'est que ce bandeau est visible sur toutes les pages du site, pas
seulement sur celle là tant que l'utilisateur n'est pas validé.

Parce qu'il est identifié sur le site (et loggué) mais pas validé. Donc il
ne recevera pas les Brief.me. C'est important d'avoir cette mention en haut
de l'écran.

2015-01-21 10:38 GMT+01:00 lmauriac <notifications@github.com>:

> Ca serait plus logique de le mettre en bas de la page après les
> explications sur le spam, etc.
>
> Deux possibilités
>
> 1-
>
> Bandeau en haut : Votre inscription n'est pas encore validée.
> Mention en bas (après point 3) : Un problème ? <lien>Renvoyer l'e-mail de
> confirmation</lien>.
>
> 2-
>
> Mention en bas (après point 3) :
> Votre inscription ne sera effective qu'après validation de l'e-mail de
> confirmation. Un problème ? <lien>Renvoyer l'e-mail de
> confirmation</lien>.
>
>
> On Wed, Jan 21, 2015 at 10:21 AM, Damien Cirotteau <
> notifications@github.com
> > wrote:
>
> > Peux tu proposer une autre formulation ?
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/briefmnews/briefme_cms/issues/140#issuecomment-70806770>
>
> > .
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/briefmnews/briefme_cms/issues/140#issuecomment-70808848>
> .
>



-- 
Damien Cirotteau

**Comment by lmauriac** [comment]
OK, alors au moins ces modifications.

Votre profil n'est pas encore validé renvoyer l'email de validation
--> Votre inscription n'est pas encore validée. <lien>Renvoyer l'e-mail de
confirmation.</lien>


2015-01-21 10:56 GMT+01:00 Damien Cirotteau <notifications@github.com>:

**Comment by cirotix** [comment]
Ok. Il y avait déjà un ticker pour ça ( #111 ). J'ai ajouté les infos de wording. Si les autres points sont ok pour toi tu peux fermer le ticket.
