### ISSUE TITLE
Modif validation-confirm

### ISSUE THREAD

**Issue by lmauriac** [briefmnews/briefme_cms#141]
http://www.brief.me:8010/validation-confirm

Manque liens réseaux sociaux.

**Comment by cirotix** [comment]
@manudurgoni cf http://share.upian.net/-Brief.me/05_User_formulaire_abonnement/05_User_formulaire_abonnement_150119.jpg

![image](https://cloud.githubusercontent.com/assets/147133/5828326/1c3522f2-a103-11e4-9288-15a78013f8df.png)

**Comment by lmauriac** [comment]
Le bouton Twitter est un peu bizarre.


On Wed, Jan 21, 2015 at 12:19 AM, Damien Cirotteau <notifications@github.com

**Comment by cirotix** [comment]
Ça sera "Suivre @briefmenews bien" sur.
Il y a différentes études qui disent que les gens utilisent plus si c'est
les boutons standards des réseaux sociaux plutôt que des boutons custom.

Si tu veux changer il faut demander à Karim.

On Wed, Jan 21, 2015 at 10:15 AM, lmauriac <notifications@github.com> wrote:

> Le bouton Twitter est un peu bizarre.
>
>
> On Wed, Jan 21, 2015 at 12:19 AM, Damien Cirotteau <
> notifications@github.com
> > wrote:
>
> > @manudurgoni <https://github.com/manudurgoni> cf
> >
> http://share.upian.net/-Brief.me/05_User_formulaire_abonnement/05_User_formulaire_abonnement_150119.jpg
> >
> > [image: image]
> > <
> https://cloud.githubusercontent.com/assets/147133/5828326/1c3522f2-a103-11e4-9288-15a78013f8df.png>
>
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/briefmnews/briefme_cms/issues/141#issuecomment-70755088>
>
> > .
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/briefmnews/briefme_cms/issues/141#issuecomment-70806108>
> .
>



-- 
Damien Cirotteau

**Comment by lmauriac** [comment]
C'est bon pour moi.


2015-01-21 10:53 GMT+01:00 Damien Cirotteau <notifications@github.com>:
