### ISSUE TITLE
Tell Laurent when ready

### ISSUE THREAD

**Issue by lmauriac** [briefmnews/briefme_cms#142]
Je ne détaille pas, j'imagine que ce n'est pas prêt. Préviens-moi quand ça l'est.

- [x] Pages archives et dernier numéro : mélange archive et CTA Essai gratuit
- [x] Les dates d'archives ne sont pas bonnes (date : 30 décembre)
- [x] Page abonnement si loggué (http://www.brief.me:8010/abonnement/)
- [ ] Pages fixes
- [x] Lien page abonnement vers archives dans menu de droite
- [x] Pas de page erreur 404

**Comment by cirotix** [comment]
> Page abonnement si loggué (http://www.brief.me:8010/abonnement/)

Qu'appelles tu loggué ? (abonné, en période d'essai, utilisateur non validé)

> Les dates d'archives ne sont pas bonnes (date : 30 décembre)

C'est "normal" c'est la version de test

**Comment by cirotix** [comment]
> Pages archives et dernier numéro : mélange archive et CTA Essai gratuit

Peux-tu être plus précis (url, problème constaté, comportement attendu) ? Je ne constate pas de problème de mon côté (cf maquette il y a un CTA quand tu n'es pas identifié). La page archive à toutes les issues repliées contrairement à la page "Dernier numéro" qui a le dernier déplié.

**Comment by lmauriac** [comment]
- Points réglés depuis le staging.

Pages archives et dernier numéro : mélange archive et CTA Essai gratuit
Page abonnement si loggué (http://www.brief.me:8010/abonnement/)
Lien page abonnement vers archives dans menu de droite

- Points en suspens

Les dates d'archives ne sont pas bonnes (date : 30 décembre)
Pages fixes non mises en ligne
Pas de page erreur 404 (page blanche actuellement)

- Ajout

Partage des articles non actif sur Facebook et G+
Lien sur Twitter ne fonctionne pas

**Comment by cirotix** [comment]
> Partage des articles non actif sur Facebook et G+

Il n'y a pas de partage G+ sur les articles. Pour Facebook il faut qu'on publie l'app demain


> Lien sur Twitter ne fonctionne pas

C'est à dire ?
