### ISSUE TITLE
Validate questions

### ISSUE THREAD

**Issue by lmauriac** [briefmnews/briefme_cms#143]
Questionnaire lien dans abo_trial_j7_email

Comment j'ai connu Brief.me
Via les réseaux sociaux
Par un article
Par un proche
Par un membre de l'équipe
Autre → préciser

Ce que j'aime le plus avec Brief.me
Brief.me m'aide à y voir clair dans l'actualité
Brief.me me sélectionne ce qui est important
Brief.me me résume l'actualité
Brief.me me fait rattraper les infos de la journée
Brief.me me fait découvir des informations pertinentes
Brief.me est un plaisir de lecture

Je lis Brief.me
Au bureau
Chez moi
Dans les transports

Quelle est la probabilité que je recommande Brief.me à un ami ou un collègue ?
Echelle de 0 à 10

Ce que Brief.me pourrait améliorer (question ouverte)

**Comment by cirotix** [comment]
Peux-tu créer le formulaire dans typeform et me donner le lien dans ce ticket ?

**Comment by cirotix** [comment]
Ah ok j'avais pas compris l'objet du ticket (je suis plus frais le matin :) )

Question 1 :
Je pense qu'on peut enlever Par un membre de l'équipe
C'est un cas qui est couvert par autre maintenant.

Ce que Brief.me pourrait améliorer en position 3 (après ce que j'aime le plus)
