### ISSUE TITLE
Modif e-mail "Une semaine avec Brief.me"

### ISSUE THREAD

**Issue by lmauriac** [briefmnews/briefme_cms#148]
Quelques modifications sont nécessaires en raison du changement de workflow (carte bancaire).

et qu'il vous est utile
--> et qu'il vous rend service

Votre période d'essai arrivera à échéance dans cinq numéros
--> dans une semaine

pour qui vous puissiez, si vous le souhaitez, résilier votre abonnement
--> pour que vous puissiez décider de poursuivre ou non votre abonnement.

Texte complet modifié ci-dessous.

--
Bonjour,

Nous avons le plaisir de vous envoyer Brief.me depuis quelques jours. Nous espérons qu'il vous aide à y voir plus clair dans l'actualité et qu'il vous rend service.

Vous pouvez bien sûr à tout moment nous dire ce que vous en pensez en nous écrivant par simple retour de mail. N'hésitez pas à nous faire part de vos critiques et à nous faire des suggestions. Depuis le début, Brief.me se construit avec ses lecteurs, en tirant parti de leurs remarques.

Nous avons préparé un petit questionnaire assez court (seulement cinq questions) pour recueillir vos premières impressions. Cela nous serait précieux d'avoir vos réponses, pour nous aider à améliorer Brief.me.

Bouton CTA : Je réponds à cinq petites questions

Votre période d'essai arrivera à échéance dans une semaine. Nous vous préviendrons le moment venu pour que vous puissiez décider de poursuivre ou non votre abonnement.

À bientôt.

Laurent Mauriac

**Comment by lmauriac** [comment]
Suggestion de Jean-Christophe.

J'ajouterais la possibilité de souscrire dès maintenant. Il y aura des gens qui seront convaincus très vite, et que ça rassurera de pouvoir s'abonner tout de suite, sans attendre le dernier moment.
Par exemple, en dernière phrase :

Votre période d'essai arrivera à échéance dans une semaine. Nous vous préviendrons le moment venu pour qui vous puissiez décider de poursuivre ou non votre abonnement. Si vous le souhaitez, vous pouvez également confirmer votre abonnement dès à présent.

Texte complet modifié ci-dessous.

--

Bonjour,

Nous avons le plaisir de vous envoyer Brief.me depuis quelques jours. Nous espérons qu'il vous aide à y voir plus clair dans l'actualité et qu'il vous rend service.

Vous pouvez bien sûr à tout moment nous dire ce que vous en pensez en nous écrivant par simple retour de mail. N'hésitez pas à nous faire part de vos critiques et à nous faire des suggestions. Depuis le début, Brief.me se construit avec ses lecteurs, en tirant parti de leurs remarques.

Nous avons préparé un petit questionnaire assez court (seulement cinq questions) pour recueillir vos premières impressions. Cela nous serait précieux d'avoir vos réponses, pour nous aider à améliorer Brief.me.

Bouton CTA : Je réponds à cinq petites questions

Votre période d'essai arrivera à échéance dans une semaine. Nous vous préviendrons le moment venu pour que vous puissiez décider de poursuivre ou non votre abonnement. Si vous le souhaitez, vous pouvez également <lien>confirmer votre abonnement</lien> dès à présent.

À bientôt.

Laurent Mauriac

**Comment by cirotix** [comment]
Ok mis à jour selon vos deux remarques. Il manque le lien vers le questionnaire.
Laurent je t'attribue le ticket pour que tu puisses vérifier puis insérer le lien vers le questionnaire. (Je vais te donner accès à Vero).
