### ISSUE TITLE
Add Recurly logo in subscribe billing_form

### ISSUE THREAD

**Issue by cirotix** [briefmnews/briefme_cms#149]
![image](https://cloud.githubusercontent.com/assets/147133/5834325/92068cd8-a15c-11e4-9f48-5b4c880f3047.png)

subscription/templates/subscription/recurly/billing_form.html

**Comment by cirotix** [comment]
Sorry it wasn't in the ticket.
Can you add a link to https://recurly.com/security/ on the logo?

**Comment by manudurgoni** [comment]
yep
