### ISSUE TITLE
Modif abonnement

### ISSUE THREAD

**Issue by lmauriac** [briefmnews/briefme_cms#150]
https://staging.brief.me/abonnement/

Annuellement
Soit 46,80 € par an
--> soit 46,80 €/an
Grossir "Soit 46,80 €/an"

Mensuellement
Supprimer "Soit 5,90 €/an"
Texte illisible (rouge sur violet)

brief.me
--> Brief.me

**Comment by cirotix** [comment]
@lmauriac  C'est la version quand tu es en connecté avec un user dont la période d'essai est activé c'est ça 
(il faut bien penser à préciser cette info (anonyme/connecté/période d'essai/payant) parce que pas mal de choses change sur le site en fonction de cet état)

**Comment by cirotix** [comment]
@manudurgoni I have remove the string / an when we are in monthly plan. This lead to blocks with different height
![image](https://cloud.githubusercontent.com/assets/147133/5838061/c68bd648-a184-11e4-9a58-c2263fa901f8.png)

Template
apps/subscription/templates/subscription/includes/block_trial_period.html

**Comment by lmauriac** [comment]
Je n'avais pas pu lire le texte précédemment.
Je pense que la deuxième partie de la phrase n'est pas suffisamment précise.

--
Annuellement
3,90 €/mois

Soit 46,80 €/an.
--> soit 46,80 €/an

Vous êtes prélevé(e) chaque année de 46,80 € et vous recevez Brief.me
pendant un an.
--> Je suis prélevé(e) chaque année de 46,80 €. J'interromps mon abonnement
quand je le souhaite.

--
Mensuellement
5,90 €/mois

Vous êtes prélevé(e) chaque mois de 5,90 € et vous recevez Brief.me pendant
un mois.
--> Je suis prélevé(e) chaque mois de 5,90 €. J'interromps mon abonnement
quand je le souhaite.

**Comment by manudurgoni** [comment]
Je vous laisse gérer ça entre vous ;)
