### ISSUE TITLE
Subscribe : change plan.choice_label 

### ISSUE THREAD

**Issue by manudurgoni** [briefmnews/briefme_cms#151]
Template : subscription/templates/subscribe.html

To match with Karim's design, can you change the choice_label to :
- `Abonnement annuel  <span class="color"><span class="big">46,80 €</span>/an  ( soit 3,90 €/mois )</span>`
- `Abonnement mensuel  <span class="color"><span class="big">5,90 €</span>/mois</span>`

![capture d ecran 2015-01-21 a 12 28 18](https://cloud.githubusercontent.com/assets/2260385/5836083/b362560a-a170-11e4-908b-77fe5c9fb498.png)

**Comment by lmauriac** [comment]
Wording

Veillez aux insécables pour ne pas avoir de retour à la ligne (€ qui
chasse).
Enlever Brief.me quotidien (inutile).
Les prix s'écrivent avec deux décimales.
On met une virgule avant les décimales (pas un point).
Pas de point après "Je m'abonne à Brief.me" (c'est un titre).


--
Je m'abonne à Brief.me

Abonnement annuel : 3,90 €/mois (soit 46,80 €/an)
Abonnement mensuel : 5,90 €/mois

**Comment by cirotix** [comment]
Already corrected on dev
