### ISSUE TITLE
Sandbox > Désabonnement

### ISSUE THREAD

**Issue by lmauriac** [briefmnews/briefme_cms#157]
Ajouter champ dynamique pour la date :

Nous avons bien reçu votre demande de désabonnement.
Votre demande sera effective dès la fin de la période en cours, le xxx.

**Comment by lmauriac** [comment]
https://app.getvero.com/template_occurrences/edit?variation_id=42817

**Comment by cirotix** [comment]
@souen You can reference this ticket for adding the date in the tracking in segment when a subscription is canceled.
Can you also send the account page url in the properties? I will need it in the email.
