### ISSUE TITLE
Sandbox > Abonnez-vous à brief.me

### ISSUE THREAD

**Issue by lmauriac** [briefmnews/briefme_cms#158]
Intervertir bloc abonnement mensuel et bloc abonnement annuel.

**Comment by cirotix** [comment]
Je ne comprends pas ce ticket.
Tout ticket se référent à une page doit comporter une URL.

**Comment by lmauriac** [comment]
https://app.getvero.com/template_occurrences/edit?variation_id=42817

**Comment by lmauriac** [comment]
https://app.getvero.com/template_occurrences/edit?variation_id=42225
