### ISSUE TITLE
Test and validate questionnaire (1 week)

### ISSUE THREAD

**Issue by lmauriac** [briefmnews/briefme_cms#184]
https://briefme.typeform.com/to/WlL4Oa

Add design elements if necessary : https://admin.typeform.com/form/307860/design/
Also include link in appropriate e-mail on Vero.

**Comment by cirotix** [comment]
Done and integrated.

On Sun, Jan 25, 2015 at 6:49 PM, lmauriac <notifications@github.com> wrote:

> Assigned #184 <https://github.com/briefmnews/briefme_cms/issues/184> to
> @cirotix <https://github.com/cirotix>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/briefmnews/briefme_cms/issues/184#event-224333554>.
>



-- 
Damien Cirotteau
