### ISSUE TITLE
Page partage articles

### ISSUE THREAD

**Issue by lmauriac** [briefmnews/briefme_cms#188]
No blank between article and footer (see screen shot).

![2015-01-26_182124](https://cloud.githubusercontent.com/assets/10548982/5904385/4216a0fc-a588-11e4-9220-5d3f22a3f656.png)

**Comment by lmauriac** [comment]
Non identifié sur le site
Windows 7
Chrome Version 40.0.2214.91 m

**Comment by cirotix** [comment]
@manu. This happen for the sharing page with share in the queries
Ex: https://www.brief.me/archives/20150126/48/214/h2OSLvXrw5Ck/?share

This happen when the news ends by a blockquote.

**Comment by manudurgoni** [comment]
I added a larger padding-bottom to the body of the sharing page.

**Comment by cirotix** [comment]
Perfect
