### ISSUE TITLE
Wording partage d'article

### ISSUE THREAD

**Issue by lmauriac** [briefmnews/briefme_cms#189]
email
--> e-mail

![2015-01-26_182313](https://cloud.githubusercontent.com/assets/10548982/5904415/74b8adc0-a588-11e4-80f0-94a33a632c97.png)

**Comment by lmauriac** [comment]
Non identifié sur le site
Windows 7
Chrome Version 40.0.2214.91 m

**Comment by cirotix** [comment]
Updated and corrected in prod
