### ISSUE TITLE
Partage Facebook

### ISSUE THREAD

**Issue by lmauriac** [briefmnews/briefme_cms#190]
Ne fonctionne pas pour moi (mais OK pour Greg et Juliette).

![2015-01-26_182422](https://cloud.githubusercontent.com/assets/10548982/5904443/b653bb80-a588-11e4-8101-5a1a6ab00775.png)

**Comment by cirotix** [comment]
Il faut préciser :

* est-ce que tu es identifié sur le site ? SI oui avec quel utilisateur
* est-ce que tu es identifié sur Facebook ? Si oui avec quel compte (et
éventuellement tester en n'étant pas connecté avec le compte Brief.me, si
c'est le cas).
* Quel navigateur utilises-tu et quel version ?

En l'état je n'ai aucun moyen de reproduire le problème puisque pour moi ça
fonctionne.

J'ai copié le mode d'emploi d'un rapport de bug que j'ai fait pour Contexte
dans le répertoire de Brief.me
https://docs.google.com/document/d/1ZZfBR1W0oGlgEIc8GOhrx8yTch3ByVO-nln_i3xwarc/edit

Il faudrait suivre la même procédure.
damien


On Mon, Jan 26, 2015 at 6:25 PM, lmauriac <notifications@github.com> wrote:

> Assigned #190 <https://github.com/briefmnews/briefme_cms/issues/190> to
> @cirotix <https://github.com/cirotix>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/briefmnews/briefme_cms/issues/190#event-224777177>.
>



-- 
Damien Cirotteau

**Comment by lmauriac** [comment]
Non identifié sur le site
Identifié sur Facebook (compte perso = compte Brief.me, ce sont les mêmes identifiants, un menu permet d'afficher soit la page perso, soit la page Brief.me)
Windows 7
Chrome Version 40.0.2214.91 m

**Comment by cirotix** [comment]
Ça arrive parce que tu es identifié sur FB en tant que Brief.me. 
![image](https://cloud.githubusercontent.com/assets/147133/5904926/94f4b2b0-a58c-11e4-9ea1-72e54d41fc49.png)

Change dans le petit menu en haut à droite sur FB et tu veras que tout fonctionne comme prévu.
(ce n'est pas juste l'affichage de la page qui change, mais bien le mode de connection)
