### ISSUE TITLE
Bullet points

### ISSUE THREAD

**Issue by lmauriac** [briefmnews/briefme_cms#196]
Dans le Brief.me du 27/01/2015 (mardi), absence de bullet points dans le "On rembobine". Elles sont pourtant présentes dans le BO.

**Comment by cirotix** [comment]
Cannot reproduce

In e-mail (Gmail on Chrome Linux)
![image](https://cloud.githubusercontent.com/assets/147133/5939327/ffdc05c0-a702-11e4-8f54-19606558fbcf.png)

In archive
![image](https://cloud.githubusercontent.com/assets/147133/5939342/220c1b26-a703-11e4-994f-87cd5ac759b2.png)

In Mailchimp
https://us8.admin.mailchimp.com/campaigns/show?id=904453
![image](https://cloud.githubusercontent.com/assets/147133/5939359/48eed512-a703-11e4-8e11-d6de1f56f912.png)

Please attach to content of the faulty email and be more explicit on how I can reproduce.

**Comment by lmauriac** [comment]
Sorry, you are right, il only happened in the test email.
