### ISSUE TITLE
Implement drip campaign in daily email

### ISSUE THREAD

**Issue by lmauriac** [briefmnews/briefme_cms#226]
Drip campaign must finalized before wednesday 25th.
Please tell Laurent about all wording needed.

Here is a reminder :

- Insérer un paragraphe en intro des Brief.me à F-7, F-3, F-1 et F=0 (F = fin période d'essai).
- Revoir la séquence du drip :
D+7 : mail avec questionnaire (D = début période d'essai)
F+1 : faux Brief.me
F+2 : relance
F+7 : questionnaire + relance
F+14 : nouvelle relance
F+21 : nouvelle relance

**Comment by cirotix** [comment]
Snippets:
drip_daily_F_-_7
drip_daily_F_-_3
drip_daily_F_-_1
drip_daily_F_0

**Comment by lmauriac** [comment]
Dis-moi si ça te va.

drip_daily_F_-7
Brief.me vous plaît ? Il vous reste encore une semaine de période d'essai.
Vous pouvez dès maintenant souscrire la suite de votre abonnement, votre
paiement sera débité dans sept jours.

drip_daily_F-3
Attention ! Plus que trois jours de période d'essai. Pour ne rater aucun
Brief.me, souscrivez maintenant la suite de votre abonnement. Votre
paiement sera débité dans trois jours

drip_daily_F-_1
Vous voici au bout de votre période d'essai. Pour recevoir Brief.me demain,
une seule solution : souscrivez votre abonnement !

drip_daily_F_0
--> le faux Brief.me


Note 1 : une petite subtilité pas forcément évidente dans la gestion des
conditions.
Il ne faut pas publier le message F-7 si un abonnement a été souscrit au
préalable.
Il ne faut pas publier le message F-3 si un abonnement a été souscrit
depuis F-7, et ainsi de suite.

Note 2 : pourrais-tu préparer un fichier complet avec l'ensemble de la
campagne drip pour relecture par Eric ?


On Wed, Feb 25, 2015 at 10:56 AM, Damien Cirotteau <notifications@github.com

**Comment by cirotix** [comment]
Je les avait fait... elles sont ici 
https://www.brief.me/admin/addendum/snippet/ 
Tu peux les changer si tu veux.

(J'avais pris en compte la subtilité, ce n'est pas très compliqué).

**Comment by cirotix** [comment]
drip_daily_F_-7
PS : Brief.me vous plaît ? Il vous reste encore une semaine de période d'essai. Vous pouvez dès maintenant souscrire la suite de votre abonnement. Votre paiement ne sera débité que dans sept jours.

drip_daily_F-3
PS : Attention ! Plus que trois jours de période d'essai. Pour ne rater aucun Brief.me, souscrivez dès maintenant la suite de votre abonnement. Si vous optez pour la formule annuelle, il ne vous en coûtera que 3,90 € par mois.

drip_daily_F-_1
PS : Voulez-vous vraiment nous quitter demain ? Ne plus recevoir votre résumé quotidien de l'actu serein et sans publicité ? Pour conserver votre rendez-vous, il vous suffit de choisir l'une de nos deux formules.

drip_daily_F-0
PS : Vous voici au bout de votre période d'essai. Pour recevoir Brief.me demain, une seule solution : souscrivez votre abonnement ! Avec Brief.me, pas de piège : notre offre est sans engagement et vous pouvez vous désinscrire facilement depuis votre compte sur notre site. A demain ?
